var tree = [["Workflux","Workflux.html","",
                [["Builder","Workflux\/Builder.html","",
                [["StateMachineBuilder","Workflux\/Builder\/StateMachineBuilder.html","",
                [        ]],["StateMachineBuilderInterface","Workflux\/Builder\/StateMachineBuilderInterface.html","",
                [        ]],["StatesVerification","Workflux\/Builder\/StatesVerification.html","",
                [        ]],["TransitionsVerification","Workflux\/Builder\/TransitionsVerification.html","",
                [        ]],["VerificationInterface","Workflux\/Builder\/VerificationInterface.html","",
                [        ]],["XmlStateMachineBuilder","Workflux\/Builder\/XmlStateMachineBuilder.html"," < StateMachineBuilder",
                [        ]]        ]],["Error","Workflux\/Error.html","",
                [["Error","Workflux\/Error\/Error.html"," < Exception",
                [        ]],["VerificationError","Workflux\/Error\/VerificationError.html"," < Error",
                [        ]]        ]],["Guard","Workflux\/Guard.html","",
                [["CallbackGuard","Workflux\/Guard\/CallbackGuard.html","",
                [        ]],["ConfigurableGuard","Workflux\/Guard\/ConfigurableGuard.html","",
                [        ]],["ExpressionGuard","Workflux\/Guard\/ExpressionGuard.html"," < ConfigurableGuard",
                [        ]],["GuardInterface","Workflux\/Guard\/GuardInterface.html","",
                [        ]],["VariableGuard","Workflux\/Guard\/VariableGuard.html"," < ExpressionGuard",
                [        ]]        ]],["Parser","Workflux\/Parser.html","",
                [["Xml","Workflux\/Parser\/Xml.html","",
                [["AbstractXmlParser","Workflux\/Parser\/Xml\/AbstractXmlParser.html","",
                [        ]],["OptionsXpathParser","Workflux\/Parser\/Xml\/OptionsXpathParser.html","",
                [        ]],["StateMachineDefinitionParser","Workflux\/Parser\/Xml\/StateMachineDefinitionParser.html"," < AbstractXmlParser",
                [        ]],["Xpath","Workflux\/Parser\/Xml\/Xpath.html"," < DOMXpath",
                [        ]]        ]],["ParserInterface","Workflux\/Parser\/ParserInterface.html","",
                [        ]]        ]],["Renderer","Workflux\/Renderer.html","",
                [["AbstractRenderer","Workflux\/Renderer\/AbstractRenderer.html","",
                [        ]],["DotGraphRenderer","Workflux\/Renderer\/DotGraphRenderer.html"," < AbstractRenderer",
                [        ]],["GraphRendererInterface","Workflux\/Renderer\/GraphRendererInterface.html","",
                [        ]]        ]],["State","Workflux\/State.html","",
                [["State","Workflux\/State\/State.html","",
                [        ]],["StateInterface","Workflux\/State\/StateInterface.html","",
                [        ]],["VariableState","Workflux\/State\/VariableState.html"," < State",
                [        ]]        ]],["StateMachine","Workflux\/StateMachine.html","",
                [["StateMachine","Workflux\/StateMachine\/StateMachine.html","",
                [        ]],["StateMachineInterface","Workflux\/StateMachine\/StateMachineInterface.html","",
                [        ]]        ]],["Transition","Workflux\/Transition.html","",
                [["Transition","Workflux\/Transition\/Transition.html","",
                [        ]],["TransitionInterface","Workflux\/Transition\/TransitionInterface.html","",
                [        ]]        ]],["ExecutionContext","Workflux\/ExecutionContext.html","",
                [        ]],["ExecutionContextInterface","Workflux\/ExecutionContextInterface.html","",
                [        ]],["StatefulSubjectInterface","Workflux\/StatefulSubjectInterface.html","",
                [        ]]        ]]        ]

